In [1]:
import pandas as pd
from numpy import *
from sklearn import *
random.seed(56115335)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.max_colwidth', 100)
pd.options.mode.chained_assignment = None  # default='warn'

## Read the data file

In [3]:
data_file = pd.read_csv('data-preprocessing/listing-processed.csv', low_memory=False).fillna(0)
data_file = data_file.loc[:, ~data_file.columns.str.contains('^Unnamed')]
data_file.shape

(24085, 68)

In [4]:
data_file

id    host_id    host_since  host_response_time  host_response_rate  host_acceptance_rate  host_is_superhost  host_listings_count  host_total_listings_count  host_verifications  host_has_profile_pic  host_identity_verified  zipcode  latitude  longitude  is_location_exact  property_type  room_type  accommodates  bathrooms  bedrooms  beds  bed_type  amenities  square_feet  price  weekly_price  monthly_price  security_deposit  cleaning_fee  guests_included  extra_people  minimum_nights  maximum_nights  minimum_minimum_nights  maximum_minimum_nights  minimum_maximum_nights  maximum_maximum_nights  minimum_nights_avg_ntm  maximum_nights_avg_ntm  has_availability  availability_30  availability_60  availability_90  availability_365  number_of_reviews  number_of_reviews_ltm  first_review   last_review  review_scores_rating  review_scores_accuracy  review_scores_cleanliness  review_scores_checkin  review_scores_communication  review_scores_location  review_scores_value  requires_license  jurisdiction_names  instant_bookable  is_business_travel_ready  cancellation_policy  require_guest_profile_picture  require_guest_phone_verification  calculated_host_listings_count  calculated_host_listings_count_entire_homes  calculated_host_listings_count_private_rooms  calculated_host_listings_count_shared_rooms  reviews_per_month
0          9835      33057  1.250784e+09                 0.0                 0.0                   0.0                  0                  1.0                        1.0                  29                     0                       0   3105.0 -37.77268  145.09213                  0             36          3             2        1.0       1.0   2.0         5         51          0.0   60.0           0.0            0.0               0.0           0.0                1          22.0               1             365                       1                       1                     365                     365                     1.0                   365.0                 1               30               60               90               365                  4                      0  1.306166e+09  1.441987e+09                  90.0                     9.0                       10.0                   10.0                         10.0                     9.0                  9.0                 0                 0.0                 0                         0                  -14                              0                                 0                               1                                            0                                             1                                            0               0.04
1         10803      38901  1.253030e+09                -1.0               100.0                   0.0                  1                  1.0                        1.0                  55                     1                       1   3057.0 -37.76651  144.98074                  1             37          3             2        1.0       1.0   1.0         4        487        226.0   35.0         200.0          803.0               0.0          11.0                1          15.0               3              30                       3                       3                      30                      30                     3.0                    30.0                 1               12               19               28               204                129                     30  1.357920e+09  1.564934e+09                  89.0                    10.0                        9.0                   10.0                          9.0                     9.0                  9.0                 0                 0.0                 1                         0                  -14                              1                                 1                               1                                            0                                             1                                            0    

## Select features and target for training and testing

#### X is features

In [5]:
X = data_file.drop(
        columns=['id', 'host_id', 'price', 'weekly_price', 'monthly_price']
    )
X.shape

(24085, 63)

#### Y is the target

In [6]:
Y = data_file['price']
Y.shape

(24085,)

#### Randomly split data into 80% train and 20% test set

In [11]:
trainX, testX, trainY, testY = \
  model_selection.train_test_split(X, Y, 
  train_size=0.80, test_size=0.20, random_state=1314)

print(trainX.shape)
print(testX.shape)

(19268, 63)
(4817, 63)


## Principal Component Analysis - PCA

In [70]:
pca = decomposition.PCA(n_components=5)
newTrainX = pca.fit_transform(trainX)
newTestX = pca.transform(testX)

In [72]:
newTestX

array([[-4.61903175e+08, -3.11111902e+07, -1.47266215e+07,
         4.38085298e+03, -2.06213487e+02],
       [-4.94008860e+08, -8.20495031e+07,  1.14160145e+07,
         9.22002767e+03, -3.49129515e+01],
       [-4.67818956e+08, -2.18942708e+07,  2.11501718e+07,
        -1.38395696e+04, -2.20038911e+02],
       ...,
       [-4.92627186e+08, -9.64808762e+07,  8.24462865e+06,
         1.30137169e+04,  1.60945428e+01],
       [-3.11773561e+08,  5.78951589e+07,  3.77706461e+07,
        -4.54412881e+04, -2.24305699e+02],
       [ 1.71723123e+09,  3.16801978e+07,  6.92469550e+06,
        -1.45828607e+04, -2.25220413e+02]])

## Decision Tree Classifier

In [43]:
dtclf = tree.DecisionTreeClassifier(random_state=1314, max_depth=10)

In [44]:
dtclf.fit(trainX, trainY)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1314, splitter='best')

In [45]:
dtclf.score(testX, testY)

0.09653311189537056

In [46]:
dtclf.feature_importances_

array([0.03765046, 0.00804609, 0.00769444, 0.        , 0.00164675,
       0.01706139, 0.00483777, 0.02860963, 0.        , 0.00375053,
       0.0365734 , 0.04616687, 0.06732971, 0.00239256, 0.        ,
       0.11997738, 0.02921472, 0.02067774, 0.04466172, 0.01847923,
       0.        , 0.03466565, 0.        , 0.01972359, 0.04507759,
       0.00846973, 0.0180483 , 0.00355063, 0.01022062, 0.0154699 ,
       0.01117119, 0.01693938, 0.00145107, 0.00200834, 0.00163246,
       0.        , 0.0176974 , 0.01114793, 0.00725384, 0.02799218,
       0.01984003, 0.00880086, 0.02565784, 0.01688165, 0.00644626,
       0.00211777, 0.00305618, 0.        , 0.00357495, 0.00777032,
       0.00338583, 0.        , 0.        , 0.00471709, 0.        ,
       0.01294685, 0.00616387, 0.        , 0.04123023, 0.02056996,
       0.02045159, 0.02521949, 0.02387903])

## Decision Tree Regressor

In [52]:
dtr = tree.DecisionTreeRegressor(random_state=1314, max_depth=10)

In [53]:
dtr.fit(trainX, trainY)

DecisionTreeRegressor(criterion='mse', max_depth=10, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=1314, splitter='best')

In [54]:
dtr.score(testX, testY)

0.07376175121009976

## KMeans

In [62]:
Ks = [i + 1 for i in range(5)]
Ks.pop(0)
Ks

[2, 3, 4, 5]

In [59]:
km = cluster.KMeans(random_state=1314, n_jobs=-1)

In [64]:
params = model_selection.ParameterGrid({'n_clusters': Ks})

In [66]:
models = []
for p in params:
    km.set_params(**p)
    Y = km.fit_predict(X)
    models.append(Y)
models

[array([0, 0, 0, ..., 1, 1, 1]),
 array([2, 2, 2, ..., 0, 0, 0]),
 array([2, 2, 2, ..., 0, 0, 0]),
 array([2, 2, 2, ..., 0, 4, 4])]